# Generated by Django 2.0.3 on 2018-04-24 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tableroMando', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicador',
            name='prefijo',
        ),
    ]
