# Generated by Django 2.0.3 on 2018-05-03 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ge1', '__first__'),
        ('tableroMando', '0003_auto_20180428_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armonizacion',
            fields=[
                ('indicador', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='tableroMando.Indicador')),
                ('tipo_proceso', models.SmallIntegerField(blank=True, choices=[(1, 'Estrategico'), (2, 'Misional'), (3, 'Apoyo'), (4, 'Evaluacion')], default=1)),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ge1.PdeUnidadNivel')),
                ('meta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ge1.PdeMetas')),
                ('proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ge1.Procesos')),
                ('programa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ge1.PdeUnidadNivel')),
                ('subprograma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ge1.PdeUnidadNivel')),
            ],
        ),
    ]
