# Generated by Django 2.0.3 on 2018-05-04 02:54

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tableroMando', '0004_armonizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicador',
            name='tipo_indicador',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Plan de desarrollo'), (2, 'Sistema de salud'), (3, 'Sistema de gestion'), (4, 'Financiero')], default='', max_length=10),
        ),
        # migrations.AlterField(
        #     model_name='indicador',
        #     name='tipo',
        #     field=models.SmallIntegerField(choices=[(1, 'Plan de desarrollo'), (2, 'Sistema de salud'), (3, 'Sistema de gestion'), (4, 'Financiero')], default=1),
        # ),
    ]
